# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exerciseId', models.AutoField(primary_key=True, serialize=False)),
                ('exerciseDescription', models.CharField(max_length=500)),
                ('exerciseTag', models.CharField(max_length=50)),
                ('exerciseData', models.DateTimeField(auto_now_add=True)),
                ('exercisePosterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SignUp')),
            ],
        ),
    ]
