# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exerciseData',
            new_name='exerciseDate',
        ),
    ]
