# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answerID', models.AutoField(primary_key=True, serialize=False)),
                ('answerDescription', models.CharField(max_length=1000)),
                ('dateAnswered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionDescription', models.CharField(max_length=1000)),
                ('dateAsked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagDescription', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('videoFile', models.FileField(upload_to=b'uploads/videos')),
            ],
        ),
        migrations.CreateModel(
            name='VideosExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exerciseId',
            new_name='exerciseID',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercisePosterId',
            new_name='exercisePosterID',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseDescription',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseTag',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseVideos',
            field=models.FileField(upload_to=b'uploads/videos'),
        ),
        migrations.AddField(
            model_name='videosexercises',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='videosexercises',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Videos'),
        ),
        migrations.AddField(
            model_name='tagsexercises',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='tagsexercises',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Tags'),
        ),
        migrations.AddField(
            model_name='questionsexercises',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='questionsexercises',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='exerciseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='questions',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answers',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseQuestions',
            field=models.ManyToManyField(through='exercise.QuestionsExercises', to='exercise.Questions'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseTag',
            field=models.ManyToManyField(through='exercise.TagsExercises', to='exercise.Tags'),
        ),
    ]
