# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_exercisevideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exerciseVideos',
            field=models.FileField(max_length=500, upload_to='./uploadVideo/'),
        ),
    ]
