# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20171012_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseTag',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseTag',
            field=models.CharField(default=b'blah', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseVideos',
            field=models.FileField(upload_to=b'./uploadVideo/'),
        ),
    ]
