# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20171012_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exerciseVideos',
            field=models.FileField(blank=True, upload_to=exercise.models.upload_location),
        ),
    ]
