# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20171012_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exerciseID',
            new_name='exerciseId',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercisePosterID',
            new_name='exercisePosterId',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseApproved',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseQuestions',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseDescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseTag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseVideos',
            field=models.FileField(max_length=500, upload_to=b'./uploadVideo/'),
        ),
    ]
