# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20171013_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagDescription', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('videoFile', models.FileField(upload_to=exercise.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='VideosExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseTag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseVideos',
        ),
        migrations.AddField(
            model_name='videosexercises',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='videosexercises',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Videos'),
        ),
        migrations.AddField(
            model_name='tagsexercises',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='tagsexercises',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Tags'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseVideos',
            field=models.ManyToManyField(through='exercise.VideosExercises', to='exercise.Videos'),
        ),
    ]
