# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0004_auto_20171013_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='exercisePosterId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
