# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20171012_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseVideos',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseVideos',
            field=models.ManyToManyField(through='exercise.VideosExercises', to='exercise.Videos'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videoFile',
            field=models.FileField(max_length=500, upload_to=b'./uploadVideo/'),
        ),
    ]
