# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20171012_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseTag',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseTag',
            field=models.ManyToManyField(through='exercise.TagsExercises', to='exercise.Tags'),
        ),
    ]
