# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20171012_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='videoPerspective',
            field=models.IntegerField(default=0),
        ),
    ]
