# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20171013_1825'),
        ('comments', '0003_auto_20171013_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='CommentExercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
            preserve_default=False,
        ),
    ]
