# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20171014_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-CommentTimestamp']},
        ),
        migrations.AddField(
            model_name='comment',
            name='CommentParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
    ]
