# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('AnnotationId', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=1000)),
                ('toVid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Videos')),
            ],
            options={
                'ordering': ['-AnnotationId'],
            },
        ),
    ]
