# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='questionParent',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='userID',
        ),
        migrations.AddField(
            model_name='questions',
            name='questionAnswer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
