# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-dateAsked']},
        ),
    ]
