# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20171201_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Description',
            new_name='Question',
        ),
    ]
